
#内嵌的Tomcat端口
server:
  port: 8090

spring:
  application:
    name: dlyk-server

  #jackson进行json转换时使用指定的时区和格式进行转换
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  #数据库
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/dlyk?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  #redis
  data:
    redis:
      host: 192.168.220.131
      port: 6379
#      password: 123456
      database: 0

