
#内嵌的Tomcat端口
server:
  port: 8088

spring:
  application:
    name: dlyk-server

  #jackson进行json转换时使用指定的时区和格式进行转换
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  #数据库
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dlyk?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  #redis
  data:
    redis:
      host: 192.168.154.100
      port: 6379
      database: 0
mybatis:
  configuration: # 配置打印 MyBatis⽇志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
